# This is a basic workflow to help you get started with Actions

name: CI

defaults:
  run:
    shell: bash -ieo pipefail {0}

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs dependencies
      - name: Install dependencies
        run: sudo apt-get install -y cmake g++-9 xorg-dev

      - name: Install pyenv
        run: |
          unset PYENV_ROOT
          curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
          echo pyenv installed!
          echo "export PATH=$HOME/.pyenv/bin:\$PATH" >> $HOME/.bashrc
          echo "eval \"\$(pyenv init -)\"" >> $HOME/.bashrc
          echo "eval \"\$(pyenv virtualenv-init -)\"" >> $HOME/.bashrc

      - name: Install scons
        run: |
          pyenv install 3.8.5
          pyenv global 3.8.5
          python -m pip install scons

      - name: Update submodules
        run: git submodule update --init --recursive

      # Build
      - name: Setup python version & Build
        run: scons

      # Runs tests
      - name: Test
        run: ./bin/RunTests
