# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Installs dependencies
      - name: Install dependencies
        run: sudo apt-get install cmake g++-9

      # Force python version
      - name: Setup python version
        run: |
          unset PYENV_ROOT
          curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
          export PATH="$HOME/.pyenv/bin:$PATH"
          pyenv init -
          pyenv virtualenv-init -
          pyenv install 3.8.5
          pyenv global 3.8.5
          python -m pip install scons

      # Clones libraries
      - name: Update submodules
        run: git submodule update --init --recursive

      # Runs builder routine
      - name: Build
        run: scons

      # Runs tests
      - name: Test
        run: ./bin/RunTests
